-- Create the security_logs table
CREATE TABLE IF NOT EXISTS security_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    content TEXT,
    violation_type TEXT,
    severity TEXT,
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE security_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Admins can view all logs
CREATE POLICY "Admins can view security logs"
    ON security_logs
    FOR SELECT
    USING (
        auth.uid() IN (
            SELECT user_id FROM admin_users
        )
    );

-- Policy: Server (service_role) can insert logs
-- Note: In Supabase, the service_role key bypasses RLS, but if we insert from client (not recommended for security logs), we'd need a policy.
-- Since we are logging from the Next.js API (backend), we will use the service_role client or ensure the user has insert rights if we use the authenticated client.
-- To be safe for authenticated users triggering alerts:
CREATE POLICY "Users can insert their own security logs"
    ON security_logs
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Optional: Allow anon inserts if we want to log attacks from unauthenticated users
CREATE POLICY "Anon can insert security logs"
    ON security_logs
    FOR INSERT
    WITH CHECK (auth.role() = 'anon');
